default_platform(:ios)

repo_url = "https://github.com/tinted-knight/ChitChat/commit/"
proj_title = "ChitChat (Timur)"

platform :ios do
  derived_data = "DerivedData/"

  desc "Installs CocoaPods deps and runs clean build"
  lane :build_for_testing do
    cocoapods
    scan(
      # clean: true,
      build_for_testing: true,
      derived_data_path: derived_data
    )
    end

  desc "Only runs app tests."
  lane :run_app_tests do
    run_tests(
      device: 'iPhone 11',
      test_without_building: true,
      derived_data_path: derived_data
    )
  end

  desc "Combines two lanes `:build_for_testing` and `:run_app_tests`"
  lane :build_and_test do
    build_for_testing
    run_app_tests
    notify_discord(
      title: proj_title, 
      text: "Build finished",
      success: true
    )
  end
end

error do
  puts "ACHTUNG"
  # notify_discord(
  #   title: "Build failed", 
  #   text: "ChitChat", 
  #   success: false
  # )
end

desc "Message to Discord via WebHook"
lane :notify_discord do |message|
  discord_notifier(
    webhook_url: ENV['DISCORD_WEBHOOK_URL'],
    title: message[:title],
    description: message[:text] + 
      "\n\n[Commit](#{repo_url}#{ENV['TRAVIS_COMMIT']})"\
      "\n#{ENV['TRAVIS_COMMIT_MESSAGE']}",
    success: message[:success],
    discord_user_id: ENV['MY_DISCORD_ID']
  )
end

desc "Test lane for Discord notification"
lane :notify_test do
  notify_discord(
    title: proj_title, 
    text: "Test notification", 
    success: true
  )
end

lane :setup_xc do
  set_xcconfig_value(
    path: 'ChitChat02/ApiConfig.xcconfig',
    name: 'API_URL_AVATAR_LIST',
    value: ENV['API_URL_AVATAR_LIST']
  )
end
